### PR TITLE
added file close for destination files

### PR DESCRIPTION
**Pull request by ritesh-pandey**
It's a quick fix which closes the destination file after writing into it.
- store file descriptor in a variable
- after all the operations on file is done, close it using the file descriptor

More code refactor needs to be done which will be taken up next.

### CODE REVIEW

**Comment by ritesh-pandey** [comment]
@shamasis I am confused with the last diff. Should a newline be present or not?

**Comment by kaustavdm** [comment]
@ritesh-pandey Looks like your text editor is configured to add a newline at the end of each file on save. That is the way it needs to be. So, keep the newline. Diff tools will be happy.

**Comment by ritesh-pandey** [comment]
@kaustavdm The editor didn't add. I added the newline manually. :)

**Comment by kaustavdm** [comment]
@ritesh-pandey Cool. Then it is high time to add "Add newline at end of file" config to your text editor :-D

**Comment by shamasis** [comment]
@ritesh-pandey - like you spotted, it needs a lot of refactor. Especially in the logic/algo. Let's do it step-by-step and we will release a new version once `lib` is refactored.

Also, an extensive testing and CI needs to be setup @rohitb4.

**Pull request merged**
