### PR TITLE
Code refactor for global variables and for-in loops

### PR DESCRIPTION
**Pull request by ritesh-pandey**
A lot of global variables are being used in lib.js
All for-in loops where iteration is being done on array has been converted to
forEach loop. This further reduces global variables.
constructorReturnCode is the new variable name for return codes from larry
constructor. This is being used in core.js. Hence a change has been done there
as well.

### CODE REVIEW

**Comment by shamasis** [comment]
In true sense, this usage of global return code is not appropriate. Our first attempt of v1 was to get it working. We should rewrite Larry from scratch and release v2.

—
Shamasis Bhattacharya

**Comment by shamasis** [comment]
@ritesh-pandey - can u resolve the conflicts and update the branch?

**Comment by ritesh-pandey** [comment]
@shamasis Resolved and updated. Please let me know if there is any other issue.

**Comment by shamasis** [comment]
@ritesh-pandey - since it is a code refactor branch where I saw that you addressed indentation and other syntax issues in some place, as such, this brach is no longer limited to loop fixing. I have done a full code re-linting of ALL files. Have a look and let me know if good to go. Possibly run a CLI test.

Once green, I will merge the branch.

**Comment by ritesh-pandey** [comment]
Ran CLI test. Everything looks good. Please go ahead.

**Pull request merged**
